<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/IDSNlogo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>


<h3> Get to Know a numpy Array </h3>


Cast the following list to a numpy array:


In [3]:

import numpy as np
a=[1,2,3,4,5]
x=np.array(a)
x

array([1, 2, 3, 4, 5])

<details><summary>Click here for the solution</summary>

```python
x = np.array(a)
```

</details>


1) Type using the function type 


In [4]:
type(x)

numpy.ndarray

<details><summary>Click here for the solution</summary>

```python
type(x)
```

</details>


2) The shape of the array 


In [5]:
x.shape

(5,)

<details><summary>Click here for the solution</summary>

```python
x.shape
```

</details>


3) The type of data in the array 


In [6]:
x.dtype

dtype('int64')

<details><summary>Click here for the solution</summary>

```python
x.dtype
```

</details>


4) Find the mean of the array 


In [7]:
x.mean

<function ndarray.mean>

In [8]:
np.array([1,-1])*np.array([1,1])

array([ 1, -1])

In [9]:
np.dot(np.array([1,-1]),np.array([1,1]))

0

<details><summary>Click here for the solution</summary>

```python
x.mean()
```

</details>


In [18]:
A=np.array([[1,2],[3,4],[5,6],[7,8]])
A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [19]:
A=np.array([[1,2],[3,4],[5,6],[7,8]])

B=np.array([[1,2,3],[4,5,6],[7,8,9]])

np.dot(A,B)

ValueError: shapes (4,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [20]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

<hr>

<h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>
